pidfile = 'api.pid'
worker_tmp_dir = '/dev/shm'
worker_class = 'gthread'
workers = 2
worker_connections = 1000
timeout = 120 # needs some time for the worker to load the model at startup
keepalive = 2
threads = 4
proc_name = 'api'
bind = '0.0.0.0:9090'
backlog = 2048
accesslog = '-'
errorlog = '-'